### ISSUE TITLE
Link to download always recent version of jython

### ISSUE THREAD

**Issue by Richienb** [jythontools/jython#107]
Just wondering, what link can I use to download the latest stable release version of Jython which never gets outdated?

If one is not available then is there one to download the latest stable release of the source code with instructions to build it?

**Comment by Stewori** [comment]
Something like
```
git clone https://github.com/jythontools/jython.git
cd jython
ant
```
should build the current dev version for you, provided git and ant are installed. (Maybe add some cleanup or better code using ``git update`` if a clone is already in place).
Depending on what you need,
``ant jar-standalone``
``ant installer``
might be the right choice.

I don't know of a suitable permanent link, other than searching maven central, e.g. ``https://mvnrepository.com/artifact/org.python/jython-standalone``.

**Comment by jeff5** [comment]
You could look it up at [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Corg.python%2Bjython), but Frank W posts milestone realeases on his blog e.g. here: http://fwierzbicki.blogspot.com/2017/07/jython-271-final-released.html .

You've already forked this repo, so you have access to the development tip. Jython is actually change-managed with Mercurial at https://hg.python.org/jython/ and magically mirrored here. Build with Ant. (See the [developer guide](https://jython-devguide.readthedocs.io/en/latest/).)

**Comment by Richienb** [comment]
Thanks for the help!
