### ISSUE TITLE
Maven artifact packages all dependencies

### ISSUE THREAD

**Issue by marianogonzalez** [jythontools/jython#11]
Hello,

I'm looking at the artefacts published at http://mvnrepository.com/artifact/org.python/jython and I see that at least versions 2.5.3 and 2.7-be are packaging all its dependencies. For example, 2.7-b3 is packaging javax:xml-apis, the sax library, etc.

This might be convenient en some cases, but when trying to use jython embedded into an already existing application, there might be version conflicts on these dependencies. Because they're embedded into the jython jar instead of being referenced dependencies into the maven pom, exclusions cannot be used to resolve the conflict.

It'd be incredible helpful to have a no-deps version of the artifact, in which dependencies are only referenced on the pom but not embedded into the jar. Anyway of getting that for the 2.7-be or 2.5.3 versions?

Thanks

**Comment by jimbaker** [comment]
Duplicates this bug: http://bugs.jython.org/issue2182

Closing out here in favor of that bug (we do not use GitHub issues...)

**Comment by ctrueden** [comment]
@marianogonzalez The way I partially got around this issue was to create a version of the jython uberjar with shaded dependencies; see [org.scijava:jython-shaded](https://github.com/scijava/jython-shaded). This is a general solution intended to be reused by anyone else who needs it.
