### ISSUE TITLE
How to run two python application in different interpreter context?

### ISSUE THREAD

**Issue by Luncert** [jythontools/jython#130]
I create two instance of PythonInterpreter in two thread to run two python application concurrently.
I found the two interpreter are sharing the same SystemState instance, which means some operation on one interpreter like setting stdout, will impact the another one, right?
So is it possible to run two interpreter concurrently and independently?

**Comment by jeff5** [comment]
This is the same (I think) as https://bugs.jython.org/issue2465 . The simple answer is that it is not possible at present to disentangle system state entirely. AFAICT this part of Jython reflects an early version of CPython plus some Java-specific adaptations to support multiple threads. I think we could do better here, but not for 2.7.2. Possibly @jimbaker has a better insight.

**Comment by Luncert** [comment]
Thanks
