### ISSUE TITLE
Compatibility with OpenJDK 12

### ISSUE THREAD

**Issue by wetneb** [jythontools/jython#146]
A deprecation warning happens when running Jython 2.7.1 with OpenJDK 12.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (.../jython-standalone-2.7.1.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

If the intention is to support recent versions of Java, this could be worth fixing.

**Comment by Stewori** [comment]
I think these are already fixed in the master branch. See discussion at https://bugs.jython.org/issue2656. Actually, it's good to know that it's still just warnings in JDK 12. I used to think Java 9 would be that last to permit this.

**Comment by wetneb** [comment]
@Stewori that's awesome! Looking forward to the new release then. Thanks for your work!
