### ISSUE TITLE
Running in background on MacOS

### ISSUE THREAD

**Issue by riklopfer** [jythontools/jython#148]
I am trying to run jython scripts in the background on MacOS. However, the process keeps stopping for no apparent reason before the main program can execute. I posted this question to stack exchange with no luck. I was hoping that someone here might have a hint. 
Ultimately, I would like to be able to do: `nohup jython script.py >& script.log &`

Here is the original post: https://apple.stackexchange.com/questions/362717/running-java-jython-process-in-the-background

Copied from the post: 

I am trying to run a Jython script in the background. This is what the script looks like, 

`a_jython_script.py`

```python
for i in range(10000):
	print i
```

When I try to run it in the background, it is stopped before it prints anything. 

```
 $ jython a_jython_script.py &
[1] 12325
 $

[1]+  Stopped                 jython a_jython_script.py
```

Sending it to the foreground allows it to continue normally. jython was installed via brew. Taking a look at what the jython startup script is doing, I can just run the Java program and get the same results. 

```
 $ /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/bin/java -Xmx512m -Xss2560k -classpath ../../../../../../usr/local/Cellar/jython/2.7.1/libexec/jython.jar:. -Dpython.home=../../../../../../usr/local/Cellar/jython/2.7.1/libexec -Dpython.executable=../../../../../../usr/local/Cellar/jython/2.7.1/libexec/bin/jython -Dpython.launcher.uname=darwin -Dpython.launcher.tty=true -Dfile.encoding=UTF-8 org.python.util.jython a_jython_script.py &
[1] 12623
 $

[1]+  Stopped                 /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/bin/java -Xmx512m -Xss2560k -classpath ../../../../../../usr/local/Cellar/jython/2.7.1/libexec/jython.jar:. -Dpython.home=../../../../../../usr/local/Cellar/jython/2.7.1/libexec -Dpython.executable=../../../../../../usr/local/Cellar/jython/2.7.1/libexec/bin/jython -Dpython.launcher.uname=darwin -Dpython.launcher.tty=true -Dfile.encoding=UTF-8 org.python.util.jython a_jython_script.py
 $
```
Adding `nohup` does not make a difference. 

Java was installed with the Oracle installer. I see the same behavior in Terminal as well as iTerm2. I do not see the same issue under Linux.

**Comment by jeff5** [comment]
I don't know, and don't have your platform to try it, but my first thought is that Jython is trying to do something with the console and being blocked. Jython at 2.7.1 rather easily believes the console is interactive and tries to install a line-editing handler. `-Dpython.launcher.tty=false` ought to convince it. There is also a way to suppress a console handler with `-Dpython.console=`. There's a bit about it [here](https://wiki.python.org/jython/ConsoleChoices).

Launching directly with Java is a good choice I think in these circumstances. You could simplify the launcher's misguided attempt to construct a relative paths from absolute ones. (Sorry 'bout that.)

**Comment by riklopfer** [comment]
That worked! Thank you. In summary, when running with `jython`, 

```
export JAVA_OPTS="-Dpython.launcher.tty=false"
jython a_jython_script.py &
```

Invoking with `java` add ` -Dpython.launcher.tty=false`

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/bin/java -Xmx512m -Xss2560k -classpath ../../../../../../usr/local/Cellar/jython/2.7.1/libexec/jython.jar:. -Dpython.home=../../../../../../usr/local/Cellar/jython/2.7.1/libexec -Dpython.executable=../../../../../../usr/local/Cellar/jython/2.7.1/libexec/bin/jython -Dpython.launcher.uname=darwin -Dpython.launcher.tty=true -Dfile.encoding=UTF-8 -Dpython.launcher.tty=false org.python.util.jython a_jython_script.py &
```
