### ISSUE TITLE
WARNING: Illegal reflective access 

### ISSUE THREAD

**Issue by fischerdr** [jythontools/jython#157]
c:\jython2.7.1>java --illegal-access=warn -jar jython.jar
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/C:/jython2.7.1/jython.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/C:/jython2.7.1/jython.jar) to field sun.nio.ch.FileChannelImpl.fd
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/C:/jython2.7.1/jython.jar) to field java.io.FileDescriptor.fd
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/C:/jython2.7.1/jython.jar) to field java.io.FileDescriptor.handle
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/C:/jython2.7.1/jython.jar) to method java.io.Console.encoding()
Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java13
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by jeff5** [comment]
https://bugs.jython.org/issue2656

These and loads more are fixed for 2.7.2, _almost_ all in fact.
