### ISSUE TITLE
Add support for Java 11

### ISSUE THREAD

**Issue by respenica** [jythontools/jython#158]
When running with Java 11 (OpenJDK Runtime Environment Corretto-11.0.5.10.1) and Jython 2.7.1, 2.7.2 Beta 1 and Beta 2, the below warning is shown:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/robotframework-3.1.2.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by jeff5** [comment]
We support Java 11. Bit more on the parallel ticket https://bugs.jython.org/issue2822
