### ISSUE TITLE
Import module from string?

### ISSUE THREAD

**Issue by kouellette** [jythontools/jython#159]
Is there a way to import a module into the interpreter via the string of a script? I know I can use `PythonInterpreter.exec(String)` to inject a given string into the local namespace but I'd like to instead inject it as a module and then access its members via the module. I've been looking at the `_imp` class which seems to be the right place but nothing obvious is jumping out at me.

If there isn't a way to currently do this, I'd be happy to take a stab at it and open a PR but figured I'd check to see if I'm just missing something.

**Comment by jeff5** [comment]
Maybe write it to a file and put the location on the `sys.path`?

Alternatively, I think you could execute the string against your own dictionary (as globals) and create a PyModule from that dictionary, to be added to sys.modules. However, I'm guessing here, and the documentation is not much help (sorry). Looking at what happens after we locate a module file (`x.py`) would give you a clue.

**Comment by kouellette** [comment]
Writing to file would certainly be the easiest approach but unfortunately would be my last option. I'm trying to keep everything within VFS to reduce visibility to the user.

I hadn't thought of your other proposal though and seems reasonable to me.

Thanks for the guidance

**Comment by Stewori** [comment]
I think, https://github.com/jythontools/jython/blob/master/src/org/python/core/imp.java#L547 might do what you want. (The String has to be presented as an InputStream, but I think it should be well possible to figure that out.) Jython might write aa Java classfile corresponding to the module to disc as a side effect. If you want to avoid that, you may be able to use https://github.com/jythontools/jython/blob/master/src/org/python/core/imp.java#L525 to get the compiled module (the would-be classfile) as a byte array. Something like https://github.com/jythontools/jython/blob/master/src/org/python/core/imp.java#L277 can turn it into a module then.

**Comment by kouellette** [comment]
Thanks! Both of these approaches work, but as you mentioned, `createFromSource` has the side effect of writing the classfiles to disk. The only change for the approach to avoid writing the classfiles was to use https://github.com/jythontools/jython/blob/master/src/org/python/core/imp.java#L818 instead of `createFromPyClass` because it's package-private but is exposed via `loadFromCompiled.`

I know have this doing what I need. Thanks for all the help!

**Comment by Stewori** [comment]
> package-private

Right, these nasty details. Glad you figured it out: "Do what I mean, not what I write."^^
