### ISSUE TITLE
please help me to uninstall it

### ISSUE THREAD

**Issue by azamet90** [jythontools/jython#162]
i get many errors on this i want to uninstall i did install from the .jar file but how to uninstall it now? completely?

**Comment by azamet90** [comment]
using kali linux

**Comment by jeff5** [comment]
Just delete it. If you've added its bin directory to your PATH or jar to CLASSPATH, then revert your additions. (AFAIK the installer will not have done that.)

Jython doesn't hook into your system in any way. If you don't run it, it just lies there quietly.
