### ISSUE TITLE
Can't install jython

### ISSUE THREAD

**Issue by joresont** [jythontools/jython#175]
The install process stop at "Inflating C:\jython2.7.2\Lib\email\test\data\msg_02.txt"
Does it need Internet to install the progrem?
I install it  without internet.

**Comment by jeff5** [comment]
I expected the installer to need the Internet at the point where it installs pip, although when I disconnected mine, installation still ran to completion. (Maybe pip has a cache.) But pip installation is beyond the point where you report trouble occurring.

As I understand it, the bulk of the installer is mostly just unzipping from the installation JAR. I've never seen it stick in the way you describe.

If it's not something trivial (like a full disk or a mis-behaving anti-virus filter) then I would try the command-line installation, or you can install with different options (choose "Custom" installation) just to see if the problem moves about.

**Comment by joresont** [comment]
> I expected the installer to need the Internet at the point where it installs pip, although when I disconnected mine, installation still ran to completion. (Maybe pip has a cache.) But pip installation is beyond the point where you report trouble occurring.
> 
> As I understand it, the bulk of the installer is mostly just unzipping from the installation JAR. I've never seen it stick in the way you describe.
> 
> If it's not something trivial (like a full disk or a mis-behaving anti-virus filter) then I would try the command-line installation, or you can install with different options (choose "Custom" installation) just to see if the problem moves about.

I tried to install jython without lib, then copy the lib from jar file to the install path. Could install completely.
Thanks for your help

**Comment by jeff5** [comment]
Mysterious problem, but thanks for posting the work-around.
