### ISSUE TITLE
Support sandbox mode?

### ISSUE THREAD

**Issue by wwhai** [jythontools/jython#177]
## I can't fond any document can support sandbox.
such this rogue program:
```python
def f():
    f()
f()
```
## I wanner run above program in a sandbox for protecd resources.

**Comment by Stewori** [comment]
Sandboxing Python is a deliberate attempt, see https://lwn.net/Articles/574215/ and https://github.com/vstinner/pysandbox. I have no reason to believe this would be different in Jython *on Python level*. However, in Jython you have the option to use Java-level sandboxing, i.e. via security managers. But this is not specific to Jython and you can check out any documentation or howto about Java sandboxing. That said, keep in mind that there have been *plenty* of security issues in Java, so you might even better move on to a process-level sandbox.
I am not aware how the common trust into Java security is as of today, but AFAIK, people kept fixing and improving the security wholes, so it may be worth a try.

**Comment by wwhai** [comment]
> Sandboxing Python is a deliberate attempt, see https://lwn.net/Articles/574215/ and https://github.com/vstinner/pysandbox. I have no reason to believe this would be different in Jython _on Python level_. However, in Jython you have the option to use Java-level sandboxing, i.e. via security managers. But this is not specific to Jython and you can check out any documentation or howto about Java sandboxing. That said, keep in mind that there have been _plenty_ of security issues in Java, so you might even better move on to a process-level sandbox.
> I am not aware how the common trust into Java security is as of today, but AFAIK, people kept fixing and improving the security wholes, so it may be worth a try.

Thank you,I am try to using jvm security mode to resolve the problem.I have fond methods to limit resource which app use.
