### ISSUE TITLE
Fedora 22: jython -v -m ensurepip ssl/tls not found!

### ISSUE THREAD

**Issue by alxgrtnstrngl** [jythontools/jython#19]
Running the following command:

sudo jython -v -m ensurepip

I get an error:

Ignoring ensurepip failure: pip 1.6 requires SSL/TLS

And pip does not install for Jython.  I'm running the full 2.7.0 Jython release on Fedora 22.  I have openssl-devel installed and I'm not sure what could be going on here.

**Comment by darjus** [comment]
Fixed since 2.7.1b2, please try it out.
