### ISSUE TITLE
How can I get jython-standalone-2.7.1.jar?

### ISSUE THREAD

**Issue by xkapil** [jythontools/jython#84]
The jar filesize is 0 bytes on Maven Central - https://mvnrepository.com/artifact/org.python/jython-standalone/2.7.1

**Comment by jeff5** [comment]
I got a 0-byte file too on my first attempt (not sure how). And it's definitely the case that on the page https://mvnrepository.com/artifact/org.python/jython-standalone/2.7.1, the metadata shows 0 bytes. But clicking "Download JAR" gives me a file around 40MB. Maybe a this is down to use of "save as" where it doesn't work, or is a quirk.

And if that doesn't work, there are definitely files with sensible sizes at: http://repo1.maven.org/maven2/org/python/jython-standalone/2.7.1/ . (Forget how I got there.)

@xkapil : Do say whether you overcame this, are still blocked, or have worked out why it might fail sometimes.
