### ISSUE TITLE
errror No module named requests

### ISSUE THREAD

**Issue by 0Chencc** [jythontools/jython#87]
I use java when calling Python error:
```Python
Import requests
ImportError: No module named requests
```
But [https://jaxenter.com/java-python-jython-2-7-beta-3-has-arrived-108027.html](https://jaxenter.com/java-python-jython-2-7-beta-3-has-arrived-108027.html) This report can be used to write requests, I do not know why I can not call

I use Jython2.7.1

Hope to reply, thank you

**Comment by jeff5** [comment]
Sorry this is still not working for you. Import is complicated and doesn't give you much clue why it fails. We will need a few facts.

1. Where is requests installed?
2. What is your sys.path when you make the import?
3. What is the result of os.uname()?
4. Did you use the pip command that came with the Jython installation to install requests? Any errors?
5. How did you work around the issue discussed here: https://github.com/jythontools/jython/issues/83#issuecomment-317493091 ?

Some difficulties arise when the host name is not ascii, as we found in issue #83 . Thanks to that report we fixed them (I hope) ready Jython 2.7.2.

**Comment by 0Chencc** [comment]
Thanks for your reply, I have successfully solved this problem

**Comment by jeff5** [comment]
That's good.

**Comment by shelja01** [comment]
@0Chencc
How did you resolve this issue?
I am trying to use Jython in ODI and getting the same error.
