### ISSUE TITLE
Python freezes in gw.remote_exec()

### ISSUE THREAD

**Issue by muh182** [jythontools/jython#99]
Greetings,

I am trying to use some java classes that I have created a Jar file, MyJarName.jar for, in Pyhton. However, when I run the code below it somehow freezes. This problem does not exist if a simple class file is used with no file structure and dependency to other JAR files.

my python code
```
import execnet
gw = execnet.makegateway("popen//python=jython")
channel = gw.remote_exec("""
 sys.path.append("/path/to/jar/file/MyJarName.jar")
 import demo.Apple as a
 apple = a()
  channel.send(apple.getCondition()l)
""")
for item in channel:
    print (item)
```

My Java Code
```
package demo;
import some.other.libraries.*;
public class Apple extends Fruit{

....
}

package demo;
import some.other.libraries.*;

public abstract class Fruit{

....
}

**Comment by jeff5** [comment]
I don't know `execnet`. It looks useful, but isn't part of Jython.

Are you able to run your code directly in Jython?

There's an obvious syntax error in `channel.send(apple.getCondition()l)`. I would guess it is failing there (unless this is just a copy-paste error), but that `execnet` as used does not convey the error output to you.

**Comment by muh182** [comment]
Thanks for your comment: 

I am working with a set of Python libraries but also part of my code is in Java. That is why I considered using Jython.

Jython is pretty great, but, doesn't quite support the python libraries I am using. All the paths are set up correctly but there still some modules that can't be imported in Jython.

So, because there was nothing else I can do to make the Python library Jython-compatible, I used execnet module to use both Python and Jython together and path variables between them.

1-channel.send(apple.getCondition()l) was a copy-paste error
2- the code works fine in Jython

**Comment by jeff5** [comment]
Regarding modules Jython can't import,  the Jython stdlib is different from the CPython one, you realise? If you put modules from CPython stdlib on the Jython path, there is invariably trouble. Are these modules that Jython can import when run normally and can't under `execnet`?

My general advice would be to get the Jython instance to spit out as much information as possible about its environment as it sees it under `execnet` (sys.path, os.environ, os.getcwd(), stream encodings, and so on). Compare that with a working Jython you launch yourself, and look for differences.

Which version of Jython are you using and on what OS? `execnet` docs only mention Jython 2.5.1, which is quite old (before my time). 2.5.1 was reasonably stable I believe, but if you discovered a bug we're very unlikely to find the effort to fix it in a 2.5.x version.

OTOH, if you're using this with 2.7.x, there could easily be differences that upset `execnet`. The launcher changed and there was some work on the console that might get in the way of `execnet` if it attaches `std*` streams. At several places in the test suite we communicate with a sub-process in roughly this way. This is always delecate, I find. The expected behaviour is more standard now, but this is no comfort to you if `execnet` has adapted to the way it used to be.

This might be a thing you have to take up with the `execnet` authors. (It would be nice to see `execnet` work with a modern Jython.)

**Comment by muh182** [comment]
Thanks for providing the suggestions. I am aware that Python modules can not be  imported in jython.

At this point, I have created a python class, the methods of which are called from the jython code. The parameters for the python functions are obtained from my Java classes. 

At this point, I would like to know if there is an easy way to include all my jar files in the Jython path.
 
For example something like `sys.path.append(path/to/lib/*.jar)`

**Comment by jeff5** [comment]
Ah, I see. Putting a JAR on the sys.path doesn't put it on the class path of the JVM: it has to be on the class path of the JVM that runs Jython, then a Python `import` statement should also find it. You can use the * form of class path with the JVM if you have a lot.

When you ran the code in Jython directly, you should have been getting an `ImportError`, so I'm a bit puzzled that "the code works fine in Jython", but maybe it fnds your JAR by default in your shell while the environment of `execnet` is different..

I suspect any hang is a secondary effect.

**Comment by muh182** [comment]
I managed to set all my jar files in the path. So now I am able to locate my class files and all the dependencies they require on Jython side. However, I am facing new issue now. When I create a new object :

```
from demo import TestUtilityOntologyNYC
ontVar = TestUtilityOntologyNYC()
```
I get this error

```
	at demo.AbstractOntologyModel.<init>(AbstractOntologyModel.java:80)
	at demo.TestUtilityOntologyNYC.<init>(TestUtilityOntologyNYC.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError
```

**Comment by muh182** [comment]
I am using Jython 2.7

**Comment by jeff5** [comment]
Good, that sounds like progress. This error is what it says it is :) something has gone wrong in your constructor, or more accurately (I think) the static initialisation of the class. The rest of it is just an account of how Jython invoked your constructor reflectively.

The natural thing to do is to single-step through the Java, which is easy if you can run your Java from the IDE.  If the problem only arises under `execnet` and/or Jython then your challenge is to launch Jython so it waits for a remote debugger to attach. For this I have a one-line DOS batch file:
`
dist\bin\jython -J-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y %*
`
The last bit means "append all the batch arguments". I use Eclipse but assume other IDEs have equivalent support.

If one is launching Jython as a subprocess, and some library function is constructing the command line, it may be difficult to get the extra -J argument into the right place without hacking on the libarry code itself.

**Comment by muh182** [comment]
Thanks for taking the time to walk me through the problem. I can run my java code through an ant file and have no problems. I managed to find out which line of the code is giving me the error and it turns out that in my constructor I have a line:

```
model = ModelFactory.createOntologyModel();
```
Which is code from a library I am using FYI. (https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/rdf/model/ModelFactory.html)

What does not make sense is why this error is not happening in Java.

I am using Jython 2.7.1 and
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
and my OS is MacOs X 10.13.2

**Comment by jeff5** [comment]
An `ExceptionInInitializerError` likely comes with information the stack dump isn't revealing. You could catch it and look at `e.getCause()`. Perhaps some jar is still missing used during the static initialisation of `ModelFactory`.

**Comment by muh182** [comment]
Thanks, still providing the same message with no additional information.

**Comment by jeff5** [comment]
I can use Jena satisfactorily from Jython at the prompt:

    PS work> ..\inst\bin\jython -J-classpath apache-jena-3.6.0\lib\*
    Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43)
    [Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_151
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from org.apache.jena.rdf.model import *
    log4j:WARN No appenders could be found for logger (Jena).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
    >>> from org.apache.jena.vocabulary import *
    >>> model = ModelFactory.createDefaultModel()
    >>> johnSmith = model.createResource("http://somewhere/JohnSmith")
    >>> johnSmith.addProperty(VCARD.FN, "John Smith")
    http://somewhere/JohnSmith

but that's not quite your case.

`demo` is your code, right? So it should be possible to experiment. The error is in the static initialisation of the class `AbstractOntologyModel`, but I thought it would be embedded in the `ExceptionInInitializerError`.

I don't see this as a Jython bug at present, but I'm curious if we've made it difficult to work with. If you can supply a short program that does this, I may be able to reproduce it.

**Comment by muh182** [comment]
I am attaching the code I have. This is a very short version of the bigger project I am working on. The sampleJython calls the java files I created` src/demo` (MyJarName.jar) + the library jar files. I bundled these two and created a `bigjythonjar.jar'  file that covers everything.   

[Here is the code](https://www.dropbox.com/s/w1e6n1zq3j6kkwf/jython.zip?dl=0)

Thank you so much for your time.

**Comment by jeff5** [comment]
I have your demo code working under Jython 2.7.0. Sorry, this is Windows PowerShell, but you'll guess what it means:
```
PS 270> dir demo


    Directory: C:\Users\Jeff\Documents\Jython\270\demo


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/02/2018     07:21           1858 AbstractOntologyModel.java
-a----       09/02/2018     07:21            283 UtilityOntology.java


PS 270> javac -classpath ".;apache-jena-3.6.0\lib\*" .\demo\*.java
PS 270> jython -J-classpath ".;apache-jena-3.6.0\lib\*"
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_151
Type "help", "copyright", "credits" or "license" for more information.
>>> import demo
>>> ontVar = demo.UtilityOntology()
**************In AbstractOntology-list of individuals created **********
log4j:WARN No appenders could be found for logger (Jena).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
**************In UtilityOntology **********
>>>
```

Jython 2.7.1 gives me an error I only half understand, but it is about encoding (which is a constant source of amusement on Windows), and different from what you report. I think this is a known (and fixed) bug that crops up when we try to produce an error message, but it leaves me wondering what the message was.

I can produce an error during static initialisation of `demo.AbstractOntologyModel`, like this:
```
   static {
       Long error = new Long(null);
   }
```
and then in Jython find out the cause:
```
>>> import demo, java.lang
>>> try:
...     ontVar = demo.UtilityOntology()
... except java.lang.Error as e:
...     pass
...
>>> e
java.lang.ExceptionInInitializerError
>>> e.getCause()
java.lang.NumberFormatException: null
```
This seems closest to what you are seeing.

**Comment by muh182** [comment]
Hi Jeff,

Thanks so much for taking the time to test my code. I tried to test it on a windows machine with  Jython 2.7 and followed your steps and it worked. However, I see a difference in the way I compile my java codes and run the Jython the code and I wonder if that is why this happens.

Step 1:
The next step for me is to replicate the process in my mac. It  seems like this line (that worked in windows) does not add all the jar files to my path in mac:
`javac -classpath ".;apache-jena-3.6.0\lib\*" .\demo\*.java`

I get many errors like this:

```
./demo/AbstractOntologyModel.java:18: error: package org.apache.jena.rdf.model does not exist
import org.apache.jena.rdf.model.*;
^
./demo/AbstractOntologyModel.java:19: error: package org.apache.jena.ontology does not exist
import org.apache.jena.ontology.*;
```


Step2:
Then, I am interested to see why it does not work the way I was doing it:
So if you look inside build.XML you will see the targets I use: "ant compile", to compile my java codes, and "ant jar" to create a big jar file of all library codes I used. I am wondering if you will get the same error if you run it the way I do it. 

Please make sure to change the `sys.path append()` input to the correct location of `build/MyJarName.jar` and `build/jar/bigjython.jar` on your machine.


```
/Users/mo/Downloads/jython 226>> jython sampleJython.py
```

I get this output:
```
**************In AbstractOntology-list of individuals created **********
log4j:WARN No appenders could be found for logger (Jena).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "sampleJython.py", line 12, in <module>
    ontVar = UtilityOntology()
	at demo.AbstractOntologyModel.<init>(AbstractOntologyModel.java:57)
	at demo.UtilityOntology.<init>(UtilityOntology.java:7)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError
/Users/mo/Downloads/jython 227>> 
```

**Comment by jeff5** [comment]
Hi Mohammad:
Glad that works on Windows for you too. The line: `javac -classpath ".;apache-jena-3.6.0\lib\*" .\demo\*.java` is obviously Windows-specific in that it uses the Microsoft backslash, and also the semicolon path separator, so on your Mac I hope you tried:
```
javac -classpath ".:apache-jena-3.6.0/lib/*" ./demo/*.java
```
or something similar. If the path separator were wrong, that would explain why Java cannot find the classes. (I haven't tested this on a Mac. I'm not sure how the shell deals with `*`.)

The `sys.path` is consulted during a Python `import` statement. Putting a JAR file on it with `sys.path.append(...)` will not help the JVM find things mentioned in your Java `import` statement.

As for the continuing `ExceptionInInitializerError`, the little snippet I gave you shows you how (in Jython) you can discover the underlying problem. I ran it like this:
```
PS jython> javac -classpath ".;build\jar\bigjython.jar" -d build  .\src\demo\*.java
PS jython> ..\..\..\inst\bin\jython -J-classpath "build;build\jar\bigjython.jar"
Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_151
Type "help", "copyright", "credits" or "license" for more information.
>>> import demo, java.lang
>>> try:
...     ontVar = demo.UtilityOntology()
... except java.lang.Error as e:
...     pass
...
**************In AbstractOntology-list of individuals created **********
log4j:WARN No appenders could be found for logger (Jena).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
>>> e
java.lang.ExceptionInInitializerError
>>> e.getCause()
java.lang.NullPointerException
>>> e.getCause().printStackTrace()
java.lang.NullPointerException
        at org.apache.jena.tdb.sys.EnvTDB.processGlobalSystemProperties(EnvTDB.java:33)
        at org.apache.jena.tdb.TDB.init(TDB.java:248)
        at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
        at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
... loads more stuff
>>>
```

You'll appreciate we're well beyond anything that might indicate Jython bug. It is interesting to see how people are using Jython, but I hope I have now given the the start that will allow you to investigate further in your own environment.

**Comment by jeff5** [comment]
I'm glad. Thanks for feeding back.

I meant to add that the mailing list [(jython-users](https://sourceforge.net/projects/jython/lists/jython-users)) may be a good place to seek help from others on using Jython. More people will see it than see the issues list.

However, if you think you've found a bug, here or bugs.jython.org is good.

**Comment by muh182** [comment]
Thanks! We will do.
